---
title: "simple_matching_diffndiff"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath("C:/Users/tenis/Desktop/Data_Projects/UT_Lab-Matching")) 
```

## Simple Matching and Diff n Diff

Because there are so many different time period, I'm going to break up the evaluation down to simple parts

```{r libraries, message=TRUE, warning=TRUE, include=FALSE}

library(tidyverse)
library(readr)
library(readxl)
library(janitor)
```

## IPD Data

```{r ipd, message=TRUE, warning=TRUE, include=FALSE}

ipd_raw <-
  read_csv("data/interim/IPD_eid_list_minus2015.csv",
           col_types = cols(X1 = col_skip()))


```

**Going from long to wide to look at those that are repeaters**

```{r long2wide}

ipdlong <- ipd_raw
ipdlong <- filter(ipdlong, year != 2015)
ipdlong <- filter(ipdlong, year != "2013/2014")
ipdlong <- ipdlong[,-2]
ipdlong$binary <- 1

ipdwide <- pivot_wider(ipdlong, names_from = year, values_from = binary) 
ipdwide[is.na(ipdwide)] <- 0
ipdwide$total_years <- rowSums(ipdwide[,c("2016","2017","2018","2019","2020")])

```

Based on the row sums, there are quite a few students who returned for multiple years.

In order to save my sanity, I'm going to look at 2016 first.

**2016**

```{r 2016}

df16 <- filter(ipd_raw, year == 2016)
```
