---
title: "measure_impact_research_labs"
author: "Ethan Tenison"
date: "5/28/2020"
output: html_document
---

```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("C:/Users/tenis/Desktop/Data_Projects/UT_Lab-Matching")) 
```

```{r libraries, include=FALSE}
library(readr)
library(dplyr)
library(Matching)
library(rbounds)


df <- read_csv("data/external/cleaned_ut_census_tea.csv", 
    col_types = cols(Time_Period = col_skip()))
  
```

```{r modifiying_gpa_mock}


df$cumulative_gpa <- df$cumulative_gpa + ifelse(df$mock_treatment == 1, runif(1, 0, 1), 0)

```

```{r propensity_score_matching}

Y <- df$cumulative_gpa
Tr <- df$mock_treatment


glm1 <- glm(Tr ~ age + citizenship + gender + ethnicities + hs_rank + c_rating + city_size, family=binomial, data = df)

# By default Match does 1-to-1 matching with replacement and estimates average treatment effect (ATT)
rr1 <- Match(Y = Y, Tr = Tr, X = glm1$fitted)

summary(rr1)
```

```{r qqplot}
qqplot(df$cumulative_gpa[rr1$index.control], df$cumulative_gpa[rr1$index.treated])
abline(coef = c(0, 1), col = 2)



```

```{r MatchBalance}

 MatchBalance(Tr ~ age +citizenship + gender + ethnicities + hs_rank + c_rating + city_size , match.out = rr1, nboots = 1000, data = df)


```

```{r sensitivity_test}

psens(rr1, Gamma=1.7, GammaInc=.05)
hlsens(rr1, Gamma=1.7, GammaInc=.05, .1)


```
